name: Test
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        echo: 123
  job2:
    if: ${{ false }}
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Testing again
  job3:
    if: ${{ false }}
    runs-on: ubuntu-latest
    needs:
      - job1
      - job2
    steps:
      - name: Testing again
