name: Test

on:
  push:
    branches:
      - main

concurrency:
  group: on-master-merge
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: simple
          config-file: "release-please-config.json"
    outputs:
      release-created: ${{ steps.release-please.outputs.release_created }}
      tag-name: ${{ steps.release-please.outputs.tag_name }}
