name: Test

on:
  push:
    branches:
      - main

concurrency:
  group: on-master-merge
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 1
  job2:
    if: ${{ 'test' == 'abc' }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 2

  job3:
    if: always() && needs.job1.result == 'success' && (needs.job2.result == 'success' || needs.job2.result == 'skipped')
    runs-on: ubuntu-latest
    needs:
      - job1
      - job2
    steps:
      - name: test
        run: echo 3
