name: Test
on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    needs:
      - name: Run Database Migration
        id: db-migration
        run: |
          echo "migrationState=Failure" >> $GITHUB_OUTPUT

      - name: ECS deploy
        if: steps.db-migration.outputs.migrationState != 'Failure'
        id: ecs-deploy
        run: |
          echo "deploymentState=Failure" >> $GITHUB_OUTPUT

      - name: Detecting failure
        if: steps.ecs-deploy.outputs.deploymentState == 'Failure' || steps.db-migration.outputs.migrationState == 'Failure'
        run: |
          echo "Failures while updating services"
          exit 1
